#include <common-lib/mpl/type-traits.h>
#include <memory>

using namespace vshalygin::cl;

static_assert(is_lvalue_static_castable_v<int, int>);
static_assert(is_lvalue_static_castable_v<int, int &>);
static_assert(is_lvalue_static_castable_v<int, int &&>);
static_assert(is_lvalue_static_castable_v<int, const int>);
static_assert(is_lvalue_static_castable_v<int, const int &>);
static_assert(is_lvalue_static_castable_v<int, const int &&>);
static_assert(is_lvalue_static_castable_v<int, volatile int>);
static_assert(is_lvalue_static_castable_v<int, volatile int &>);
static_assert(is_lvalue_static_castable_v<int, volatile int &&>);
static_assert(is_lvalue_static_castable_v<int, const volatile int>);
static_assert(is_lvalue_static_castable_v<int, const volatile int &>);
static_assert(is_lvalue_static_castable_v<int, const volatile int &&>);

static_assert(is_lvalue_static_castable_v<int &, int>);
static_assert(is_lvalue_static_castable_v<int &, int &>);
static_assert(is_lvalue_static_castable_v<int &, int &&>);
static_assert(is_lvalue_static_castable_v<int &, const int>);
static_assert(is_lvalue_static_castable_v<int &, const int &>);
static_assert(is_lvalue_static_castable_v<int &, const int &&>);
static_assert(is_lvalue_static_castable_v<int &, volatile int>);
static_assert(is_lvalue_static_castable_v<int &, volatile int &>);
static_assert(is_lvalue_static_castable_v<int &, volatile int &&>);
static_assert(is_lvalue_static_castable_v<int &, const volatile int>);
static_assert(is_lvalue_static_castable_v<int &, const volatile int &>);
static_assert(is_lvalue_static_castable_v<int &, const volatile int &&>);

static_assert(is_lvalue_static_castable_v<int &&, int>);
static_assert(is_lvalue_static_castable_v<int &&, int &>);
static_assert(is_lvalue_static_castable_v<int &&, int &&>);
static_assert(is_lvalue_static_castable_v<int &&, const int>);
static_assert(is_lvalue_static_castable_v<int &&, const int &>);
static_assert(is_lvalue_static_castable_v<int &&, const int &&>);
static_assert(is_lvalue_static_castable_v<int &&, volatile int>);
static_assert(is_lvalue_static_castable_v<int &&, volatile int &>);
static_assert(is_lvalue_static_castable_v<int &&, volatile int &&>);
static_assert(is_lvalue_static_castable_v<int &&, const volatile int>);
static_assert(is_lvalue_static_castable_v<int &&, const volatile int &>);
static_assert(is_lvalue_static_castable_v<int &&, const volatile int &&>);

static_assert(is_lvalue_static_castable_v<const int, int>);
static_assert(!is_lvalue_static_castable_v<const int, int &>);
static_assert(!is_lvalue_static_castable_v<const int, int &&>);
static_assert(is_lvalue_static_castable_v<const int, const int>);
static_assert(is_lvalue_static_castable_v<const int, const int &>);
static_assert(is_lvalue_static_castable_v<const int, const int &&>);
static_assert(is_lvalue_static_castable_v<const int, volatile int>);
static_assert(!is_lvalue_static_castable_v<const int, volatile int &>);
static_assert(!is_lvalue_static_castable_v<const int, volatile int &&>);
static_assert(is_lvalue_static_castable_v<const int, const volatile int>);
static_assert(is_lvalue_static_castable_v<const int, const volatile int &>);
static_assert(is_lvalue_static_castable_v<const int, const volatile int &&>);

static_assert(is_lvalue_static_castable_v<const int &, int>);
static_assert(!is_lvalue_static_castable_v<const int &, int &>);
static_assert(!is_lvalue_static_castable_v<const int &, int &&>);
static_assert(is_lvalue_static_castable_v<const int &, const int>);
static_assert(is_lvalue_static_castable_v<const int &, const int &>);
static_assert(is_lvalue_static_castable_v<const int &, const int &&>);
static_assert(is_lvalue_static_castable_v<const int &, volatile int>);
static_assert(!is_lvalue_static_castable_v<const int &, volatile int &>);
static_assert(!is_lvalue_static_castable_v<const int &, volatile int &&>);
static_assert(is_lvalue_static_castable_v<const int &, const volatile int>);
static_assert(is_lvalue_static_castable_v<const int &, const volatile int &>);
static_assert(is_lvalue_static_castable_v<const int &, const volatile int &&>);

static_assert(is_lvalue_static_castable_v<const int &&, int>);
static_assert(!is_lvalue_static_castable_v<const int &&, int &>);
static_assert(!is_lvalue_static_castable_v<const int &&, int &&>);
static_assert(is_lvalue_static_castable_v<const int &&, const int>);
static_assert(is_lvalue_static_castable_v<const int &&, const int &>);
static_assert(is_lvalue_static_castable_v<const int &&, const int &&>);
static_assert(is_lvalue_static_castable_v<const int &&, volatile int>);
static_assert(!is_lvalue_static_castable_v<const int &&, volatile int &>);
static_assert(!is_lvalue_static_castable_v<const int &&, volatile int &&>);
static_assert(is_lvalue_static_castable_v<const int &&, const volatile int>);
static_assert(is_lvalue_static_castable_v<const int &&, const volatile int &>);
static_assert(is_lvalue_static_castable_v<const int &&, const volatile int &&>);

static_assert(is_lvalue_static_castable_v<volatile int, int>);
static_assert(!is_lvalue_static_castable_v<volatile int, int &>);
static_assert(!is_lvalue_static_castable_v<volatile int, int &&>);
static_assert(is_lvalue_static_castable_v<volatile int, const int>);
static_assert(!is_lvalue_static_castable_v<volatile int, const int &>);
static_assert(!is_lvalue_static_castable_v<volatile int, const int &&>);
static_assert(is_lvalue_static_castable_v<volatile int, volatile int>);
static_assert(is_lvalue_static_castable_v<volatile int, volatile int &>);
static_assert(is_lvalue_static_castable_v<volatile int, volatile int &&>);
static_assert(is_lvalue_static_castable_v<volatile int, const volatile int>);
static_assert(is_lvalue_static_castable_v<volatile int, const volatile int &>);
static_assert(is_lvalue_static_castable_v<volatile int, const volatile int &&>);

static_assert(is_lvalue_static_castable_v<volatile int &, int>);
static_assert(!is_lvalue_static_castable_v<volatile int &, int &>);
static_assert(!is_lvalue_static_castable_v<volatile int &, int &&>);
static_assert(is_lvalue_static_castable_v<volatile int &, const int>);
static_assert(!is_lvalue_static_castable_v<volatile int &, const int &>);
static_assert(!is_lvalue_static_castable_v<volatile int &, const int &&>);
static_assert(is_lvalue_static_castable_v<volatile int &, volatile int>);
static_assert(is_lvalue_static_castable_v<volatile int &, volatile int &>);
static_assert(is_lvalue_static_castable_v<volatile int &, volatile int &&>);
static_assert(is_lvalue_static_castable_v<volatile int &, const volatile int>);
static_assert(is_lvalue_static_castable_v<volatile int &, const volatile int &>);
static_assert(is_lvalue_static_castable_v<volatile int &, const volatile int &&>);

static_assert(is_lvalue_static_castable_v<const int &&, int>);
static_assert(!is_lvalue_static_castable_v<const int &&, int &>);
static_assert(!is_lvalue_static_castable_v<const int &&, int &&>);
static_assert(is_lvalue_static_castable_v<const int &&, const int>);
static_assert(is_lvalue_static_castable_v<const int &&, const int &>);
static_assert(is_lvalue_static_castable_v<const int &&, const int &&>);
static_assert(is_lvalue_static_castable_v<const int &&, volatile int>);
static_assert(!is_lvalue_static_castable_v<const int &&, volatile int &>);
static_assert(!is_lvalue_static_castable_v<const int &&, volatile int &&>);
static_assert(is_lvalue_static_castable_v<const int &&, const volatile int>);
static_assert(is_lvalue_static_castable_v<const int &&, const volatile int &>);
static_assert(is_lvalue_static_castable_v<const int &&, const volatile int &&>);

static_assert(is_lvalue_static_castable_v<const volatile int, int>);
static_assert(!is_lvalue_static_castable_v<const volatile int, int &>);
static_assert(!is_lvalue_static_castable_v<const volatile int, int &&>);
static_assert(is_lvalue_static_castable_v<const volatile int, const int>);
static_assert(!is_lvalue_static_castable_v<const volatile int, const int &>);
static_assert(!is_lvalue_static_castable_v<const volatile int, const int &&>);
static_assert(is_lvalue_static_castable_v<const volatile int, volatile int>);
static_assert(!is_lvalue_static_castable_v<const volatile int, volatile int &>);
static_assert(!is_lvalue_static_castable_v<const volatile int, volatile int &&>);
static_assert(is_lvalue_static_castable_v<const volatile int, const volatile int>);
static_assert(is_lvalue_static_castable_v<const volatile int, const volatile int &>);
static_assert(is_lvalue_static_castable_v<const volatile int, const volatile int &&>);

static_assert(is_lvalue_static_castable_v<const volatile int &, int>);
static_assert(!is_lvalue_static_castable_v<const volatile int &, int &>);
static_assert(!is_lvalue_static_castable_v<const volatile int &, int &&>);
static_assert(is_lvalue_static_castable_v<const volatile int &, const int>);
static_assert(!is_lvalue_static_castable_v<const volatile int &, const int &>);
static_assert(!is_lvalue_static_castable_v<const volatile int &, const int &&>);
static_assert(is_lvalue_static_castable_v<const volatile int &, volatile int>);
static_assert(!is_lvalue_static_castable_v<const volatile int &, volatile int &>);
static_assert(!is_lvalue_static_castable_v<const volatile int &, volatile int &&>);
static_assert(is_lvalue_static_castable_v<const volatile int &, const volatile int>);
static_assert(is_lvalue_static_castable_v<const volatile int &, const volatile int &>);
static_assert(is_lvalue_static_castable_v<const volatile int &, const volatile int &&>);

static_assert(is_lvalue_static_castable_v<const volatile int &&, int>);
static_assert(!is_lvalue_static_castable_v<const volatile int &&, int &>);
static_assert(!is_lvalue_static_castable_v<const volatile int &&, int &&>);
static_assert(is_lvalue_static_castable_v<const volatile int &&, const int>);
static_assert(!is_lvalue_static_castable_v<const volatile int &&, const int &>);
static_assert(!is_lvalue_static_castable_v<const volatile int &&, const int &&>);
static_assert(is_lvalue_static_castable_v<const volatile int &&, volatile int>);
static_assert(!is_lvalue_static_castable_v<const volatile int &&, volatile int &>);
static_assert(!is_lvalue_static_castable_v<const volatile int &&, volatile int &&>);
static_assert(is_lvalue_static_castable_v<const volatile int &&, const volatile int>);
static_assert(is_lvalue_static_castable_v<const volatile int &&, const volatile int &>);
static_assert(is_lvalue_static_castable_v<const volatile int &&, const volatile int &&>);

static_assert(is_lvalue_static_castable_v<int, double>);
static_assert(!is_lvalue_static_castable_v<int, double &>);
static_assert(is_lvalue_static_castable_v<int, double &&>);
static_assert(is_lvalue_static_castable_v<int, const double>);
static_assert(is_lvalue_static_castable_v<int, const double &>);
static_assert(is_lvalue_static_castable_v<int, const double &&>);
static_assert(is_lvalue_static_castable_v<int, volatile double>);
static_assert(!is_lvalue_static_castable_v<int, volatile double &>);
static_assert(is_lvalue_static_castable_v<int, volatile double &&>);
static_assert(is_lvalue_static_castable_v<int, const volatile double>);
static_assert(!is_lvalue_static_castable_v<int, const volatile double &>);
static_assert(is_lvalue_static_castable_v<int, const volatile double &&>);

static_assert(is_lvalue_static_castable_v<int &, double>);
static_assert(!is_lvalue_static_castable_v<int &, double &>);
static_assert(is_lvalue_static_castable_v<int &, double &&>);
static_assert(is_lvalue_static_castable_v<int &, const double>);
static_assert(is_lvalue_static_castable_v<int &, const double &>);
static_assert(is_lvalue_static_castable_v<int &, const double &&>);
static_assert(is_lvalue_static_castable_v<int &, volatile double>);
static_assert(!is_lvalue_static_castable_v<int &, volatile double &>);
static_assert(is_lvalue_static_castable_v<int &, volatile double &&>);
static_assert(is_lvalue_static_castable_v<int &, const volatile double>);
static_assert(!is_lvalue_static_castable_v<int &, const volatile double &>);
static_assert(is_lvalue_static_castable_v<int &, const volatile double &&>);

static_assert(is_lvalue_static_castable_v<int &&, double>);
static_assert(!is_lvalue_static_castable_v<int &&, double &>);
static_assert(is_lvalue_static_castable_v<int &&, double &&>);
static_assert(is_lvalue_static_castable_v<int &&, const double>);
static_assert(is_lvalue_static_castable_v<int &&, const double &>);
static_assert(is_lvalue_static_castable_v<int &&, const double &&>);
static_assert(is_lvalue_static_castable_v<int &&, volatile double>);
static_assert(!is_lvalue_static_castable_v<int &&, volatile double &>);
static_assert(is_lvalue_static_castable_v<int &&, volatile double &&>);
static_assert(is_lvalue_static_castable_v<int &&, const volatile double>);
static_assert(!is_lvalue_static_castable_v<int &&, const volatile double &>);
static_assert(is_lvalue_static_castable_v<int &&, const volatile double &&>);

static_assert(is_lvalue_static_castable_v<const int, double>);
static_assert(!is_lvalue_static_castable_v<const int, double &>);
static_assert(is_lvalue_static_castable_v<const int, double &&>);
static_assert(is_lvalue_static_castable_v<const int, const double>);
static_assert(is_lvalue_static_castable_v<const int, const double &>);
static_assert(is_lvalue_static_castable_v<const int, const double &&>);
static_assert(is_lvalue_static_castable_v<const int, volatile double>);
static_assert(!is_lvalue_static_castable_v<const int, volatile double &>);
static_assert(is_lvalue_static_castable_v<const int, volatile double &&>);
static_assert(is_lvalue_static_castable_v<const int, const volatile double>);
static_assert(!is_lvalue_static_castable_v<const int, const volatile double &>);
static_assert(is_lvalue_static_castable_v<const int, const volatile double &&>);

static_assert(is_lvalue_static_castable_v<const int &, double>);
static_assert(!is_lvalue_static_castable_v<const int &, double &>);
static_assert(is_lvalue_static_castable_v<const int &, double &&>);
static_assert(is_lvalue_static_castable_v<const int &, const double>);
static_assert(is_lvalue_static_castable_v<const int &, const double &>);
static_assert(is_lvalue_static_castable_v<const int &, const double &&>);
static_assert(is_lvalue_static_castable_v<const int &, volatile double>);
static_assert(!is_lvalue_static_castable_v<const int &, volatile double &>);
static_assert(is_lvalue_static_castable_v<const int &, volatile double &&>);
static_assert(is_lvalue_static_castable_v<const int &, const volatile double>);
static_assert(!is_lvalue_static_castable_v<const int &, const volatile double &>);
static_assert(is_lvalue_static_castable_v<const int &, const volatile double &&>);

static_assert(is_lvalue_static_castable_v<const int &&, double>);
static_assert(!is_lvalue_static_castable_v<const int &&, double &>);
static_assert(is_lvalue_static_castable_v<const int &&, double &&>);
static_assert(is_lvalue_static_castable_v<const int &&, const double>);
static_assert(is_lvalue_static_castable_v<const int &&, const double &>);
static_assert(is_lvalue_static_castable_v<const int &&, const double &&>);
static_assert(is_lvalue_static_castable_v<const int &&, volatile double>);
static_assert(!is_lvalue_static_castable_v<const int &&, volatile double &>);
static_assert(is_lvalue_static_castable_v<const int &&, volatile double &&>);
static_assert(is_lvalue_static_castable_v<const int &&, const volatile double>);
static_assert(!is_lvalue_static_castable_v<const int &&, const volatile double &>);
static_assert(is_lvalue_static_castable_v<const int &&, const volatile double &&>);

static_assert(is_lvalue_static_castable_v<volatile int, double>);
static_assert(!is_lvalue_static_castable_v<volatile int, double &>);
static_assert(is_lvalue_static_castable_v<volatile int, double &&>);
static_assert(is_lvalue_static_castable_v<volatile int, const double>);
static_assert(is_lvalue_static_castable_v<volatile int, const double &>);
static_assert(is_lvalue_static_castable_v<volatile int, const double &&>);
static_assert(is_lvalue_static_castable_v<volatile int, volatile double>);
static_assert(!is_lvalue_static_castable_v<volatile int, volatile double &>);
static_assert(is_lvalue_static_castable_v<volatile int, volatile double &&>);
static_assert(is_lvalue_static_castable_v<volatile int, const volatile double>);
static_assert(!is_lvalue_static_castable_v<volatile int, const volatile double &>);
static_assert(is_lvalue_static_castable_v<volatile int, const volatile double &&>);

static_assert(is_lvalue_static_castable_v<volatile int &, double>);
static_assert(!is_lvalue_static_castable_v<volatile int &, double &>);
static_assert(is_lvalue_static_castable_v<volatile int &, double &&>);
static_assert(is_lvalue_static_castable_v<volatile int &, const double>);
static_assert(is_lvalue_static_castable_v<volatile int &, const double &>);
static_assert(is_lvalue_static_castable_v<volatile int &, const double &&>);
static_assert(is_lvalue_static_castable_v<volatile int &, volatile double>);
static_assert(!is_lvalue_static_castable_v<volatile int &, volatile double &>);
static_assert(is_lvalue_static_castable_v<volatile int &, volatile double &&>);
static_assert(is_lvalue_static_castable_v<volatile int &, const volatile double>);
static_assert(!is_lvalue_static_castable_v<volatile int &, const volatile double &>);
static_assert(is_lvalue_static_castable_v<volatile int &, const volatile double &&>);

static_assert(is_lvalue_static_castable_v<volatile int &&, double>);
static_assert(!is_lvalue_static_castable_v<volatile int &&, double &>);
static_assert(is_lvalue_static_castable_v<volatile int &&, double &&>);
static_assert(is_lvalue_static_castable_v<volatile int &&, const double>);
static_assert(is_lvalue_static_castable_v<volatile int &&, const double &>);
static_assert(is_lvalue_static_castable_v<volatile int &&, const double &&>);
static_assert(is_lvalue_static_castable_v<volatile int &&, volatile double>);
static_assert(!is_lvalue_static_castable_v<volatile int &&, volatile double &>);
static_assert(is_lvalue_static_castable_v<volatile int &&, volatile double &&>);
static_assert(is_lvalue_static_castable_v<volatile int &&, const volatile double>);
static_assert(!is_lvalue_static_castable_v<volatile int &&, const volatile double &>);
static_assert(is_lvalue_static_castable_v<volatile int &&, const volatile double &&>);

static_assert(is_lvalue_static_castable_v<const volatile int, double>);
static_assert(!is_lvalue_static_castable_v<const volatile int, double &>);
static_assert(is_lvalue_static_castable_v<const volatile int, double &&>);
static_assert(is_lvalue_static_castable_v<const volatile int, const double>);
static_assert(is_lvalue_static_castable_v<const volatile int, const double &>);
static_assert(is_lvalue_static_castable_v<const volatile int, const double &&>);
static_assert(is_lvalue_static_castable_v<const volatile int, volatile double>);
static_assert(!is_lvalue_static_castable_v<const volatile int, volatile double &>);
static_assert(is_lvalue_static_castable_v<const volatile int, volatile double &&>);
static_assert(is_lvalue_static_castable_v<const volatile int, const volatile double>);
static_assert(!is_lvalue_static_castable_v<const volatile int, const volatile double &>);
static_assert(is_lvalue_static_castable_v<const volatile int, const volatile double &&>);

static_assert(is_lvalue_static_castable_v<const volatile int &, double>);
static_assert(!is_lvalue_static_castable_v<const volatile int &, double &>);
static_assert(is_lvalue_static_castable_v<const volatile int &, double &&>);
static_assert(is_lvalue_static_castable_v<const volatile int &, const double>);
static_assert(is_lvalue_static_castable_v<const volatile int &, const double &>);
static_assert(is_lvalue_static_castable_v<const volatile int &, const double &&>);
static_assert(is_lvalue_static_castable_v<const volatile int &, volatile double>);
static_assert(!is_lvalue_static_castable_v<const volatile int &, volatile double &>);
static_assert(is_lvalue_static_castable_v<const volatile int &, volatile double &&>);
static_assert(is_lvalue_static_castable_v<const volatile int &, const volatile double>);
static_assert(!is_lvalue_static_castable_v<const volatile int &, const volatile double &>);
static_assert(is_lvalue_static_castable_v<const volatile int &, const volatile double &&>);

static_assert(is_lvalue_static_castable_v<const volatile int &&, double>);
static_assert(!is_lvalue_static_castable_v<const volatile int &&, double &>);
static_assert(is_lvalue_static_castable_v<const volatile int &&, double &&>);
static_assert(is_lvalue_static_castable_v<const volatile int &&, const double>);
static_assert(is_lvalue_static_castable_v<const volatile int &&, const double &>);
static_assert(is_lvalue_static_castable_v<const volatile int &&, const double &&>);
static_assert(is_lvalue_static_castable_v<const volatile int &&, volatile double>);
static_assert(!is_lvalue_static_castable_v<const volatile int &&, volatile double &>);
static_assert(is_lvalue_static_castable_v<const volatile int &&, volatile double &&>);
static_assert(is_lvalue_static_castable_v<const volatile int &&, const volatile double>);
static_assert(!is_lvalue_static_castable_v<const volatile int &&, const volatile double &>);
static_assert(is_lvalue_static_castable_v<const volatile int &&, const volatile double &&>);


static_assert(is_lvalue_static_castable_v<std::unique_ptr<int>, bool>);
static_assert(is_lvalue_static_castable_v<std::unique_ptr<int> &, bool>);
static_assert(is_lvalue_static_castable_v<std::unique_ptr<int> &&, bool>);
static_assert(is_lvalue_static_castable_v<const std::unique_ptr<int>, bool>);
static_assert(is_lvalue_static_castable_v<const std::unique_ptr<int> &, bool>);
static_assert(is_lvalue_static_castable_v<const std::unique_ptr<int> &&, bool>);
static_assert(!is_lvalue_static_castable_v<volatile std::unique_ptr<int>, bool>);
static_assert(!is_lvalue_static_castable_v<volatile std::unique_ptr<int> &, bool>);
static_assert(!is_lvalue_static_castable_v<volatile std::unique_ptr<int> &&, bool>);
static_assert(!is_lvalue_static_castable_v<const volatile std::unique_ptr<int>, bool>);
static_assert(!is_lvalue_static_castable_v<const volatile std::unique_ptr<int> &, bool>);
static_assert(!is_lvalue_static_castable_v<const volatile std::unique_ptr<int> &&, bool>);
