#include <common-lib/mpl/function-transform.h>

using namespace vshalygin::cl;

namespace {
    class t
    {};
}

static_assert(std::is_same_v<make_function_type_t<void()>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(&)()>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(&&)()>, void()>);
static_assert(std::is_same_v<make_function_type_t<void() noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(&)() noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(&&)() noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(*)()>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(* &)()>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(* &&)()>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(* const)()>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(* const &)()>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(* const &&)()>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(* volatile)()>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(* volatile &)()>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(* volatile &&)()>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(* const volatile)()>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(* const volatile &)()>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(* const volatile &&)()>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(*)() noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(*&)() noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(*&&)() noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(*const)() noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(*const &)() noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(*const &&)() noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(*volatile)() noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(*volatile &)() noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(*volatile &&)() noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(*const volatile)() noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(*const volatile &)() noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(*const volatile &&)() noexcept>, void()>);

static_assert(std::is_same_v<make_function_type_t<void(t::*)()>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: * &)()>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: * &&)()>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const)()>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &)()>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &&)()>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile)()>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &)()>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &&)()>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile)()>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &)()>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &&)()>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *)() const>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&)() const>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&&)() const>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const)() const>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &)() const>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &&)() const>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile)() const>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &)() const>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &&)() const>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile)() const>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &)() const>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &&)() const>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *)() volatile>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&)() volatile>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&&)() volatile>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const)() volatile>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &)() volatile>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &&)() volatile>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile)() volatile>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &)() volatile>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &&)() volatile>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile)() volatile>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &)() volatile>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &&)() volatile>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *)() const volatile>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&)() const volatile>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&&)() const volatile>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const)() const volatile>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &)() const volatile>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &&)() const volatile>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile)() const volatile>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &)() const volatile>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &&)() const volatile>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile)() const volatile>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &)() const volatile>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &&)() const volatile>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *)() noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&)() noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&&)() noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const)() noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &)() noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &&)() noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile)() noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &)() noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &&)() noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile)() noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &)() noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &&)() noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *)() const noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&)() const noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&&)() const noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const)() const noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &)() const noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &&)() const noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile)() const noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &)() const noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &&)() const noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile)() const noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &)() const noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &&)() const noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *)() volatile noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&)() volatile noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&&)() volatile noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const)() volatile noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &)() volatile noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &&)() volatile noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile)() volatile noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &)() volatile noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &&)() volatile noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile)() volatile noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &)() volatile noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &&)() volatile noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *)() const volatile noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&)() const volatile noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&&)() const volatile noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const)() const volatile noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &)() const volatile noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &&)() const volatile noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile)() const volatile noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &)() const volatile noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &&)() const volatile noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile)() const volatile noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &)() const volatile noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &&)() const volatile noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *)() &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&)() &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&&)() &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const)() &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &)() &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &&)() &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile)() &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &)() &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &&)() &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile)() &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &)() &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &&)() &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *)() const &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&)() const &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&&)() const &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const)() const &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &)() const &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &&)() const &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile)() const &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &)() const &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &&)() const &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile)() const &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &)() const &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &&)() const &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *)() volatile &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&)() volatile &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&&)() volatile &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const)() volatile &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &)() volatile &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &&)() volatile &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile)() volatile &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &)() volatile &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &&)() volatile &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile)() volatile &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &)() volatile &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &&)() volatile &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *)() const volatile &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&)() const volatile &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&&)() const volatile &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const)() const volatile &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &)() const volatile &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &&)() const volatile &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile)() const volatile &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &)() const volatile &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &&)() const volatile &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile)() const volatile &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &)() const volatile &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &&)() const volatile &>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *)() & noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&)() & noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&&)() & noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const)() & noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &)() & noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &&)() & noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile)() & noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &)() & noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &&)() & noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile)() & noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &)() & noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &&)() & noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *)() const &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&)() const &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&&)() const &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const)() const &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &)() const &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &&)() const &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile)() const &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &)() const &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &&)() const &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile)() const &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &)() const &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &&)() const &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *)() volatile &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&)() volatile &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&&)() volatile &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const)() volatile &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &)() volatile &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &&)() volatile &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile)() volatile &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &)() volatile &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &&)() volatile &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile)() volatile &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &)() volatile &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &&)() volatile &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *)() const volatile &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&)() const volatile &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&&)() const volatile &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const)() const volatile &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &)() const volatile &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &&)() const volatile &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile)() const volatile &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &)() const volatile &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &&)() const volatile &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile)() const volatile &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &)() const volatile &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &&)() const volatile &noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *)() &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&)() &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&&)() &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const)() &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &)() &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &&)() &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile)() &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &)() &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &&)() &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile)() &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &)() &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &&)() &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *)() const &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&)() const &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&&)() const &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const)() const &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &)() const &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &&)() const &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile)() const &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &)() const &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &&)() const &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile)() const &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &)() const &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &&)() const &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *)() volatile &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&)() volatile &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&&)() volatile &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const)() volatile &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &)() volatile &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &&)() volatile &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile)() volatile &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &)() volatile &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &&)() volatile &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile)() volatile &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &)() volatile &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &&)() volatile &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *)() const volatile &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&)() const volatile &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&&)() const volatile &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const)() const volatile &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &)() const volatile &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &&)() const volatile &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile)() const volatile &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &)() const volatile &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &&)() const volatile &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile)() const volatile &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &)() const volatile &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &&)() const volatile &&>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *)() && noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&)() && noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&&)() && noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const)() && noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &)() && noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &&)() && noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile)() && noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &)() && noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &&)() && noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile)() && noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &)() && noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &&)() && noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *)() const &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&)() const &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&&)() const &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const)() const &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &)() const &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &&)() const &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile)() const &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &)() const &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &&)() const &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile)() const &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &)() const &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &&)() const &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *)() volatile &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&)() volatile &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&&)() volatile &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const)() volatile &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &)() volatile &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &&)() volatile &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile)() volatile &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &)() volatile &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &&)() volatile &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile)() volatile &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &)() volatile &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &&)() volatile &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *)() const volatile &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&)() const volatile &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *&&)() const volatile &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const)() const volatile &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &)() const volatile &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const &&)() const volatile &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile)() const volatile &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &)() const volatile &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *volatile &&)() const volatile &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile)() const volatile &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &)() const volatile &&noexcept>, void()>);
static_assert(std::is_same_v<make_function_type_t<void(t:: *const volatile &&)() const volatile &&noexcept>, void()>);
